# Generated by Django 5.2.7 on 2025-10-23 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='request_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='donationrecord',
            old_name='donation_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'A-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='requester_name',
            field=models.CharField(help_text="Hospital or individual's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='units_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='units_donated',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
